name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [x86, amd64, amd64_arm, amd64_arm64]
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Compile
        run: nmake
      - name: Package
        shell: powershell
        run: |
          $convey_version = [regex]::Match([IO.File]::ReadAllText("config.h"), 'VERSION\s*"([^"]+)"').captures.groups[1].value
          $ZIPBALL="convey-" + $convey_version + "-" + ($env:ARCH -Replace ".*_") + ".zip"
          7z a $ZIPBALL convey.exe convey.pdb LICENSE README.md
