name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        arch: [x86, amd64, amd64_arm, amd64_arm64]
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Prepare environment vars
        shell: powershell
        run: |
          echo ("GITHUB_SHA_SHORT=" + $env:GITHUB_SHA.substring(0, 7)) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append 
          $convey_version = [regex]::Match([IO.File]::ReadAllText("Makefile"), 'VERSION\s*=\s*(\S+)').captures.groups[1].value
          echo ("CONVEY_VERSION=" + $convey_version) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append 
          $target_arch = $env:Platform -Replace ".*_"
          echo ("TARGET_ARCH=" + $target_arch) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append 
          echo ("RELEASE_ASSET_NAME=convey-" + $convey_version + "-" + $target_arch + ".zip") | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Compile convey release tag
        run: nmake
      - name: Package release build
        run: |
          7z a ${{ env.RELEASE_ASSET_NAME }} convey.exe convey.pdb LICENSE README.md
      - name: Upload release build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.RELEASE_ASSET_NAME }}
          asset_name: ${{ env.RELEASE_ASSET_NAME }}
          asset_content_type: application/zip

